steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/jude-406314/jude', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/jude-406314/jude']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'jude'
    - '--image'
    - 'gcr.io/jude-406314/jude'
    - '--set-env-vars'
    - 'DB_USER=root,DB_PASS=passworddbjude,DB_NAME=db_jude,INSTANCE_HOST=35.238.19.176,DB_PORT=3306,SECRET_KEY="iR0FfMkRs51UaWiaxF1WOtgwwrdaXuQmCJTIa3KmvK2TbH0ERdTpKZBrjug1fbtb"'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'  # Remove if not needed
    - '--port'
    - '8080'  # Update with your Node.js application port
    - '--memory'
    - '256Mi'  # Update with your preferred memory limit
    - '--cpu'
    - '1'  # Update with your preferred CPU limit
images:
- 'gcr.io/jude-406314/jude'